theme: jekyll-theme-cayman
title: Leaflet routing machine typed definition documentation
description: The documentation of Typescript definition for leaflet routing machine
google_analytics: UA-77736216-3
github:
  repository_url: https://github.com/chanakadrathnayaka/DefinitelyTyped/tree/master/types/leaflet-routing-machine
