theme: jekyll-theme-cayman
title: TypeScript Definition for leaflet-routing-machine.js
description: Use leaflet routing machine in your TypeScript project
google_analytics: UA-77736216-3
github:
  repository_url: https://github.com/chanakadrathnayaka/DefinitelyTyped/tree/master/types/leaflet-routing-machine
